version: "3.9"

services:
  bot:
    build: ./bot
    container_name: reg_bot
    restart: always
    env_file:
      - ./bot/.env.production
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: reg_redis
    restart: always
    ports:
      - "6379:6379"
